### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by oatmealraisin** [Suhmedoh/themer.edit#3]
On line 435, my python is hitting an "invalid syntax" error when running the script.

I checked all the prereqs.  Running i3-gaps, no lemon, arch linux

lmk if you need any more information!

**Comment by Suhmedoh** [comment]
did you already install it all fine? can you paste the exact command you use to run the program and the error?  when you run it send me the whole output.  I'll look into it in the mean time and see if i can figure it out without all the info.

Thanks!

**Comment by oatmealraisin** [comment]
I believe I have installed everything right.  The error occurs whenever any command is invoked.

> $ ./themer.py list
> $ File "./themer.py", line 435
> $     print '\n'.join(sorted(themes))
> $               ^
> $ SyntaxError: invalid syntax

**Comment by Suhmedoh** [comment]
do me a favor and join #doughpit on irc.rizon.net, it'll be easier to talk and figure this out, and I'll post the solution on here for anyone else that has the same problem 

SOLVED: the script needs to be run with Python 2.7, because the print function is different (2.7 uses print, 3.5 uses print())

Change #!/usr/bin/env python at the top of themer.py to #!/usr/bin/env python2.7

will fix that in the next commit
